# Generated by Django 5.2.7 on 2025-10-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام آزمون')),
                ('test_type', models.CharField(choices=[('big_five', 'پنج عامل بزرگ شخصیت'), ('mbti', 'MBTI'), ('disc', 'DISC'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع آزمون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'آزمون شخصیتی',
                'verbose_name_plural': 'آزمون\u200cهای شخصیتی',
            },
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_files/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('resume', 'رزومه'), ('portfolio', 'نمونه کار'), ('certificate', 'گواهینامه'), ('project', 'پروژه'), ('other', 'سایر')], max_length=20, verbose_name='نوع فایل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'فایل دانشجو',
                'verbose_name_plural': 'فایل\u200cهای دانشجو',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='شماره دانشجویی')),
                ('university', models.CharField(max_length=200, verbose_name='دانشگاه')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('degree_level', models.CharField(choices=[('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=50, verbose_name='مقطع تحصیلی')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='سال فارغ\u200cالتحصیلی')),
                ('gpa', models.FloatField(blank=True, null=True, verbose_name='معدل')),
                ('is_student_verified', models.BooleanField(default=False, verbose_name='احراز هویت دانشجویی')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='verification_documents/', verbose_name='مدرک احراز هویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل\u200cهای دانشجو',
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('job_type', models.CharField(choices=[('internship', 'کارآموزی'), ('part_time', 'نیمه\u200cوقت'), ('full_time', 'تمام\u200cوقت'), ('project', 'پروژه\u200cای'), ('freelance', 'فریلنسری')], max_length=20, verbose_name='نوع شغل')),
                ('work_type', models.CharField(choices=[('remote', 'دورکاری'), ('office', 'حضوری'), ('hybrid', 'ترکیبی')], max_length=20, verbose_name='نوع کار')),
                ('skills', models.TextField(verbose_name='مهارت\u200cها')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('is_available_for_employment', models.BooleanField(default=True, verbose_name='قابل استخدام')),
                ('expected_salary', models.IntegerField(blank=True, null=True, verbose_name='حقوق مورد انتظار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'درخواست دانشجو',
                'verbose_name_plural': 'درخواست\u200cهای دانشجو',
            },
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='نمره')),
                ('result_data', models.JSONField(verbose_name='داده\u200cهای نتیجه')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تکمیل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.personalitytest', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون',
                'verbose_name_plural': 'نتایج آزمون\u200cها',
                'unique_together': {('student', 'test')},
            },
        ),
    ]
