# Generated by Django 5.2.7 on 2025-10-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('company_type', models.CharField(choices=[('startup', 'استارتاپ'), ('small', 'شرکت کوچک'), ('medium', 'شرکت متوسط'), ('large', 'شرکت بزرگ'), ('multinational', 'چندملیتی')], max_length=100, verbose_name='نوع شرکت')),
                ('industry', models.CharField(max_length=100, verbose_name='صنعت')),
                ('company_size', models.CharField(choices=[('1-10', '1-10 نفر'), ('11-50', '11-50 نفر'), ('51-200', '51-200 نفر'), ('201-500', '201-500 نفر'), ('500+', 'بیش از 500 نفر')], max_length=50, verbose_name='اندازه شرکت')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات شرکت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='company_verification/', verbose_name='مدرک تایید شرکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل شرکت',
                'verbose_name_plural': 'پروفایل\u200cهای شرکت',
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغل')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی مورد نیاز')),
                ('job_type', models.CharField(choices=[('internship', 'کارآموزی'), ('part_time', 'نیمه\u200cوقت'), ('full_time', 'تمام\u200cوقت'), ('project', 'پروژه\u200cای')], max_length=20, verbose_name='نوع شغل')),
                ('work_type', models.CharField(choices=[('remote', 'دورکاری'), ('office', 'حضوری'), ('hybrid', 'ترکیبی')], max_length=20, verbose_name='نوع کار')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('required_skills', models.TextField(verbose_name='مهارت\u200cهای مورد نیاز')),
                ('min_age', models.IntegerField(blank=True, null=True, verbose_name='حداقل سن')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='حداکثر سن')),
                ('min_salary', models.IntegerField(blank=True, null=True, verbose_name='حداقل حقوق')),
                ('max_salary', models.IntegerField(blank=True, null=True, verbose_name='حداکثر حقوق')),
                ('number_of_positions', models.IntegerField(default=1, verbose_name='تعداد موقعیت\u200cهای شغلی')),
                ('description', models.TextField(verbose_name='توضیحات شغل')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='الزامات')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='مزایا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'درخواست شغلی',
                'verbose_name_plural': 'درخواست\u200cهای شغلی',
            },
        ),
    ]
