# Generated by Django 5.2.7 on 2025-10-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام معیار')),
                ('weight', models.FloatField(default=1.0, verbose_name='وزن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'معیار مچینگ',
                'verbose_name_plural': 'معیارهای مچینگ',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(verbose_name='امتیاز مچینگ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('company_message', models.TextField(blank=True, null=True, verbose_name='پیام شرکت')),
                ('student_message', models.TextField(blank=True, null=True, verbose_name='پیام دانشجو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_company', to=settings.AUTH_USER_MODEL, verbose_name='شرکت')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='companies.jobrequest', verbose_name='درخواست شغلی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_student', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('student_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='students.studentrequest', verbose_name='درخواست دانشجو')),
            ],
            options={
                'verbose_name': 'مچینگ',
                'verbose_name_plural': 'مچینگ\u200cها',
                'unique_together': {('student', 'job_request')},
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ایجاد شده'), ('viewed', 'مشاهده شده'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('contacted', 'تماس گرفته شده')], max_length=20, verbose_name='عمل')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='matching.match', verbose_name='مچینگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه مچینگ',
                'verbose_name_plural': 'تاریخچه مچینگ\u200cها',
            },
        ),
    ]
