# Generated by Django 5.2.7 on 2025-10-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('image', 'تصویر')], default='text', max_length=20, verbose_name='نوع پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/', verbose_name='ضمیمه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('match', 'مچینگ جدید'), ('message', 'پیام جدید'), ('verification', 'تایید احراز هویت'), ('test_result', 'نتیجه آزمون'), ('job_offer', 'پیشنهاد شغل'), ('system', 'سیستم')], max_length=20, verbose_name='نوع نوتیفیکیشن')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شیء مرتبط')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع شیء مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن',
                'verbose_name_plural': 'نوتیفیکیشن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
